### ISSUE TITLE
Firefox 41.0.1 crashes with fontconfig-infinality-ultimate-2.11.1-30 on archlinux

### ISSUE THREAD

**Issue by totakura** [bohoomil/fontconfig-ultimate#111]
This issue is similar to #58.  The crash happens as in the referenced bug.  Here is a stack trace:
```
(gdb) bt
#0  0x00007f1174ca0c39 in raise () from /usr/lib/libpthread.so.0
#1  0x00007f1171689776 in ?? () from /usr/lib/firefox/libxul.so
#2  0x00007f1171996b14 in ?? () from /usr/lib/firefox/libxul.so
#3  <signal handler called>
#4  0x00007f116d21a7f1 in ?? () from /usr/lib/libfontconfig.so.1
#5  0x00007f116d21a927 in ?? () from /usr/lib/libfontconfig.so.1
#6  0x00007f116d21b831 in FcConfigSubstituteWithPat ()
   from /usr/lib/libfontconfig.so.1
#7  0x00007f116d22a06c in FcFontRenderPrepare ()
   from /usr/lib/libfontconfig.so.1
#8  0x00007f1171cfc9c7 in ?? () from /usr/lib/firefox/libxul.so
#9  0x00007f1171cfdb10 in ?? () from /usr/lib/firefox/libxul.so
```
The fix suggested in #58 is applied in my setup

**Comment by bohoomil** [comment]
We no longer use the configuration from November 2014, so no such "fix" can be applied. Please, revise and update your fontconfig-iu installation as it seems to be causing the problems.
